Repository yiisoft/hydrator, pull requests merged in 2023-05, with the labels that each got.

#9 Rename "model" to "object"
  rector.php
  src/Hydrator.php
  src/HydratorInterface.php
  tests/Attribute/Data/MapTest.php
  tests/Attribute/Data/StrictTest.php
  tests/Attribute/Parameter/DataTest.php
  tests/Attribute/Parameter/DiResolverTest.php
  tests/Attribute/Parameter/ToStringTest.php
  tests/Attribute/SkipHydrationTest.php
  tests/HydratorTest.php
  tests/Support/Classes/ConstructorParameterAttributesClass.php
  tests/Support/Classes/ConstructorTypeClass.php
  tests/Support/Classes/CounterClass.php
  tests/Support/Classes/FromPredefinedArrayClass.php
  tests/Support/Classes/InvalidDataResolverClass.php
  tests/Support/Classes/MapClass.php
  tests/Support/Classes/NestedModel/Name.php
  tests/Support/Classes/NestedModel/UserModel.php
  tests/Support/Classes/ObjectPropertyModel/Car.php
  tests/Support/Classes/ObjectPropertyModel/ObjectPropertyModel.php
  tests/Support/Classes/ObjectPropertyModel/RedCar.php
  tests/Support/Classes/PreparePropertyClass.php
  tests/Support/Classes/SimpleClass.php
  tests/Support/Classes/SkipHydrationClass.php
  tests/Support/Classes/StaticClass.php
  tests/Support/Classes/StrictClass.php
  tests/Support/Classes/TypeClass.php
  tests/TestEnvironments/Php81/HydratorTest.php
  tests/TestEnvironments/Php81/Support/ReadonlyClass.php
  tests/TestEnvironments/Php81/Support/TypeObject.php
Labels: status:code review

#12 Make `Data` constructor parameters optional
  src/Data.php
Labels: status:code review

#13 Remove `Hydrator` from `TypeCasterInterface`
  src/Hydrator.php
  src/TypeCaster/CompositeTypeCaster.php
  src/TypeCaster/NoTypeCaster.php
  src/TypeCaster/SimpleTypeCaster.php
  src/TypeCasterInterface.php
  tests/Support/String42TypeCaster.php
Labels: status:code review

#14 Add type caster to `ParameterAttributesHandler`
  src/ParameterAttributesHandler.php
  tests/ParameterAttributesHandlerTest.php
  tests/Support/Attribute/Value.php
  tests/Support/SkipTypeCaster.php
  tests/Support/TestHelper.php
Labels: status:code review

#15 Increase MSI
  phpunit.xml.dist
  tests/Attribute/SkipHydrationTest.php
  tests/DataTest.php
  tests/HydratorTest.php
  tests/ParameterAttributesHandlerTest.php
  tests/Support/Attribute/ContextViewer.php
  tests/Support/Attribute/ContextViewerResolver.php
  tests/Support/Classes/SkipHydrationClass.php
  tests/Support/Classes/StaticClass.php
  tests/Support/Classes/TypeClass.php
  tests/TestEnvironments/Php81/HydratorTest.php
  tests/TestEnvironments/Php81/Support/ReadonlyClass.php
  tests/TestEnvironments/Php82/HydratorTest.php
  tests/TestEnvironments/Php82/Support/CarInterface.php
  tests/TestEnvironments/Php82/Support/StringableCar.php
  tests/TestEnvironments/Php82/Support/TypeObject.php
  tests/TypeCaster/SimpleTypeCasterTest.php
  tests/UnexpectedAttributeExceptionTest.php
Labels: status:code review, type:test

#16 Merge `Map` and `Strict` data attributes
  .styleci.yml
  src/Attribute/Data/Map.php
  src/Attribute/Data/Strict.php
  tests/Attribute/Data/MapTest.php
  tests/Attribute/Data/StrictTest.php
  tests/Support/Classes/MapNonStrictClass.php
  tests/Support/Classes/MapStrictClass.php
Labels: status:code review

#21 Make key in `Data` attribute required
  src/Attribute/Parameter/Data.php
  src/Context.php
  tests/Attribute/Parameter/DataTest.php
  tests/ContextTest.php
Labels: status:code review

#22 Allow use `Di` attribute without ID
  src/Attribute/Parameter/Di.php
  src/Attribute/Parameter/DiNotFoundException.php
  src/Attribute/Parameter/DiResolver.php
  tests/Attribute/Parameter/DiResolverTest.php
  tests/Attribute/Parameter/DiTest.php
  tests/Support/Classes/DiSingle.php
  tests/Support/Classes/DiSingleConstructor.php
  tests/Support/Classes/DiSingleNulledWithDefault.php
  tests/Support/Classes/DiSingleNulledWithDefaultConstructor.php
  tests/Support/Classes/DiSingleWithoutType.php
  tests/Support/Classes/DiSingleWithoutTypeConstructor.php
  tests/Support/Classes/DiUnion.php
  tests/Support/Classes/DiUnionWithDefault.php
  tests/Support/Classes/DiUnionWithDefaultConstructor.php
  tests/Support/Classes/Engine1.php
  tests/Support/Classes/EngineInterface.php
Labels: status:code review

#24 Use result object instead of exception for type cast control flow
  src/Hydrator.php
  src/ParameterAttributesHandler.php
  src/SkipTypeCastException.php
  src/TypeCastResult.php
  src/TypeCaster/CompositeTypeCaster.php
  src/TypeCaster/NoTypeCaster.php
  src/TypeCaster/SimpleTypeCaster.php
  src/TypeCasterInterface.php
  tests/Support/SkipTypeCaster.php
  tests/Support/String42TypeCaster.php
Labels: status:code review

#23 Improve `Map` attribute tests
  tests/Attribute/Data/MapTest.php
  tests/Support/Classes/MapClass.php
  tests/Support/Classes/MapNonStrictClass.php
  tests/Support/Classes/MapStrictClass.php
  tests/Support/CustomData.php
Labels: status:code review

#25 Use single `Value` for type cast and resolve value flow
  src/Attribute/Parameter/Data.php
  src/Attribute/Parameter/DiResolver.php
  src/Attribute/Parameter/ToString.php
  src/Context.php
  src/DataHelper.php
  src/Hydrator.php
  src/NotResolvedException.php
  src/ParameterAttributeResolverInterface.php
  src/ParameterAttributesHandler.php
  src/TypeCaster/CompositeTypeCaster.php
  src/TypeCaster/NoTypeCaster.php
  src/TypeCaster/SimpleTypeCaster.php
  src/TypeCasterInterface.php
  src/Value.php
  tests/ContextTest.php
  tests/ParameterAttributesHandlerTest.php
  tests/Support/Attribute/ContextViewerResolver.php
  tests/Support/Attribute/CounterResolver.php
  tests/Support/Attribute/CustomValue.php
  tests/Support/Attribute/FromPredefinedArrayResolver.php
  tests/Support/SkipTypeCaster.php
  tests/Support/String42TypeCaster.php
Labels: status:code review

#19 Docs
  README.md
  src/Attribute/Data/Map.php
  src/Attribute/Parameter/Data.php
  src/Attribute/Parameter/Di.php
  src/Attribute/Parameter/DiNotFoundException.php
  src/Attribute/Parameter/DiResolver.php
  src/Attribute/Parameter/ToString.php
  src/Attribute/SkipHydration.php
  src/Context.php
  src/Data.php
  src/DataAttributeInterface.php
  src/DataAttributeResolverInterface.php
  src/DataAttributesHandler.php
  src/DataHelper.php
  src/Hydrator.php
  src/HydratorInterface.php
  src/ParameterAttributeInterface.php
  src/ParameterAttributeResolverInterface.php
  src/ParameterAttributesHandler.php
  src/Result.php
  src/TypeCaster/CompositeTypeCaster.php
  src/TypeCaster/NoTypeCaster.php
  src/TypeCaster/SimpleTypeCaster.php
  src/TypeCasterInterface.php
  src/UnexpectedAttributeException.php
  tests/ReadMe/Car.php
  tests/ReadMe/Engine.php
  tests/ReadMe/Money.php
  tests/ReadMe/Person1.php
  tests/ReadMe/Person2.php
  tests/ReadMe/ReadMeTest.php
Labels: type:docs
